# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7054e3ed-a4d2-4d8b-b64f-2373b2e064c7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e1cc17fb-f461-4f88-82ce-fa36f0b6ae1f".device = "/dev/disk/by-uuid/e1cc17fb-f461-4f88-82ce-fa36f0b6ae1f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/79EA-C309";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/841af9ec-829e-4bd0-93c7-eef2d75724cf"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp44s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
