name: 'rebuild-deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test-runner:
    runs-on: ["Xiaomi Book 16"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: /tmp/Github
