name: 'rebuild-deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    with:
      path: /home/alex/Documents/Github
jobs:
  test-runner:
    runs-on: [self-hosted]
    steps:
      - name: Delay for 10 seconds
        run: |
          echo "Delaying for 10 seconds..."
          sleep 10
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delay for 10 seconds
        run: |
          echo "Delaying for 10 seconds..."
          sleep 10
      - name: Update flake
        run: nix flake update
      - name: print directory
        run: pwd
      - name: Rebuild laptop
        run: |
          nixos-rebuild switch --flake .#laptop 
