name: 'rebuild-deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test-runner:
    runs-on: ["Xiaomi Book 16"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download wireguard configuration
        run: |
          echo "${{ secrets.WIREGUARD_XIAOMI_BOOK_16 }}" > "./modules/wireguard/Xiaomi Book 16.conf"
      - name: Import WireGuard Connection
        run: |
          nmcli connection import type wireguard file "./modules/wireguard/Xiaomi Book 16.conf"
        #with:
        #  path: /tmp/Github
