name: 'rebuild-deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  test-runner:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update flake
        run: sudo nix flake update
      - name: Rebuild laptop
        run: sudo nixos-rebuild switch --flake .#laptop 