name: 'rebuild-deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  test-runner:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Rebuild NixOS
        run: |
          which sudo
          echo $PATH
          id