name: 'rebuild-deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    #with:
    #  path: /home/alex/Documents/temp
jobs:
  test-runner:
    runs-on: [self-hosted]
    steps:
      - name: Print PATH
        run: echo $PATH
      - name: Add NixOS PATH
        run: export PATH=/run/current-system/sw/bin/nixos-rebuild:$PATH
      - name: Print PATH
        run: echo $PATH
      - name: print directory
        run: pwd
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update flake
        run: nix flake update
      - name: print directory
        run: pwd
      - name: list
        run: ls
      - name: Rebuild laptop
        run: |
          nixos-rebuild switch --flake .#laptop 
